export const LUCIDE_ICONS_LIST = [
  { value: "", label: "None (Use Image)" },
  { value: "Activity", label: "Activity" },
  { value: "AlertTriangle", label: "Alert Triangle" },
  { value: "Archive", label: "Archive" },
  { value: "Award", label: "Award" },
  { value: "Banknote", label: "Banknote" },
  { value: "BookOpen", label: "Book Open" },
  { value: "Briefcase", label: "Briefcase" },
  { value: "Building", label: "Building" },
  { value: "Building2", label: "Building 2" },
  { value: "Camera", label: "Camera" },
  { value: "CheckCircle", label: "Check Circle" },
  { value: "CheckSquare", label: "Check Square" },
  { value: "Clock", label: "Clock" },
  { value: "Compass", label: "Compass" },
  { value: "CreditCard", label: "Credit Card" },
  { value: "Crosshair", label: "Crosshair" },
  { value: "Database", label: "Database" },
  { value: "Edit", label: "Edit" },
  { value: "Eye", label: "Eye" },
  { value: "File", label: "File" },
  { value: "FileCheck", label: "File Check" },
  { value: "FileSearch", label: "File Search" },
  { value: "FileText", label: "File Text" },
  { value: "Flag", label: "Flag" },
  { value: "Folder", label: "Folder" },
  { value: "Globe", label: "Globe" },
  { value: "HardHat", label: "Hard Hat" },
  { value: "Heart", label: "Heart" },
  { value: "Home", label: "Home" },
  { value: "Image", label: "Image" },
  { value: "Info", label: "Info" },
  { value: "Key", label: "Key" },
  { value: "Landmark", label: "Landmark" },
  { value: "LifeBuoy", label: "Life Buoy" },
  { value: "Link", label: "Link" },
  { value: "Lock", label: "Lock" },
  { value: "Mail", label: "Mail" },
  { value: "MapPin", label: "Map Pin" },
  { value: "Monitor", label: "Monitor" },
  { value: "Navigation", label: "Navigation" },
  { value: "Package", label: "Package" },
  { value: "Phone", label: "Phone" },
  { value: "PieChart", label: "Pie Chart" },
  { value: "Search", label: "Search" },
  { value: "Settings", label: "Settings" },
  { value: "Shield", label: "Shield" },
  { value: "ShieldCheck", label: "Shield Check" },
  { value: "Star", label: "Star" },
  { value: "Target", label: "Target" },
  { value: "Terminal", label: "Terminal" },
  { value: "Tool", label: "Tool" },
  { value: "Unlock", label: "Unlock" },
  { value: "User", label: "User" },
  { value: "UserCheck", label: "User Check" },
  { value: "Users", label: "Users" },
];